# Generated by Django 5.2.6 on 2025-10-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
