# Generated by Django 5.2.6 on 2025-10-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_cart_rename_custom_user_customuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='modeltest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
