# Generated by Django 5.2.6 on 2025-10-11 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
