# Generated by Django 5.2.6 on 2025-10-08 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_product_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
