# Generated by Django 5.2.6 on 2025-10-13 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrating',
            name='average_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
